version: "3.3"
services:
  contacts-api:
    container_name: contacts-api
    build:
      context: ./
      dockerfile: ./src/Contacts/Contacts.Api/dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=docker
        - AzureAD:ClientId=<secret>
        - AzureAD:ClientSecret=<secret>

  contacts-publisher:
    container_name: contacts-notificationpublisher
    build:
      context: ./
      dockerfile: ./src/Contacts/Contacts.NotificationPublisher/dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=docker
        - AzureAD:ClientId=<secret>
        - AzureAD:ClientSecret=<secret>

  communications-api:
    container_name: communications-api
    build:
      context: ./
      dockerfile: ./src/Communications/Communications.Api/dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=docker
        - AzureAD:ClientId=<secret>
        - AzureAD:ClientSecret=<secret>

  communications-backend:
    build:
      context: ./
      dockerfile: ./src/Communications/Communications.Backend/dockerfile
    environment:
        - NETCORE_ENVIRONMENT=docker
        - AzureAD:ClientId=<secret>
        - AzureAD:ClientSecret=<secret>

  frontend:
    build:
      context: ./
      dockerfile: ./src/FrontEnd/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ServiceEndpoints:ContactsService=http://contacts-api:80
      - ServiceEndpoints:NotificationService=http://communications-api:80
    ports:
      - "9600:80"
