FROM microsoft/dotnet:sdk AS build-env

# Copy csproj and restore as distinct layers
WORKDIR /src

WORKDIR /src/Shared/Domain
COPY /src/Shared/Domain/Domain.csproj .
RUN dotnet restore

WORKDIR /src/Communications/Communications.Messages
COPY /src/Communications/Communications.Messages/Communications.Messages.csproj .
RUN dotnet restore

WORKDIR /src/Contacts/Contacts.Messages
COPY /src/Contacts/Contacts.Messages/Contacts.Messages.csproj .
RUN dotnet restore

WORKDIR /src/FrontEnd
COPY /src/FrontEnd/FrontEnd.csproj .
RUN dotnet restore


# Copy everything else and build
COPY /src/Shared/Domain/ /src/Shared/Domain/
COPY /src/Communications/Communications.Messages/ /src/Communications/Communications.Messages/
COPY /src/Contacts/Contacts.Messages/ /src/Contacts/Contacts.Messages/
COPY /src/FrontEnd/ ./src/FrontEnd/
WORKDIR /src/FrontEnd

RUN dotnet publish -c Release -o /out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "FrontEnd.dll"]
